// Domain layer: transfer rules for Sprint D4 (D4 Transfer, Batch 1).
// A transfer moves money between TWO of the caller's own wallets and is
// recorded as ONE transaction row of type 'transfer' - the approved D4
// model decision (the ROADMAP build order #4 fork, discussed pre-coding;
// see supabase/migrations/20261002090000_add_transfers.sql for the
// full rationale).
//
// Approved D4 design decisions (do not "improve" without re-approval):
//   - One row: `wallet_id` = SOURCE, `to_wallet_id` = DESTINATION, both
//     always set. A transfer whose endpoint fails to resolve never
//     reaches this domain - the chat handler falls back to the ordinary
//     recording path first (D4 fail-open decision), so by the time we
//     are here both endpoints already matched active wallets by name.
//   - category is always the built-in 'Transfer' (transactions.category
//     is NOT NULL; the ten-default list has carried 'Transfer' since the
//     init migration - D1 made names free text, the default still
//     exists).
//   - Deterministic, never LLM-produced: confidence 'high',
//     prompt_version null (SPECIFICATION.md 12.3 - no extraction ran to
//     produce this row).
//   - Ownership + active state are re-checked HERE at commit (both
//     endpoints must exist, belong to the caller, and not be archived) -
//     the same defense-in-depth the D3 budget confirm re-check uses.
//     Archived wallets are refused: decision B keeps archived rows out
//     of NEW recordings.
//   - No new state and no confirmation step: the chat flow inserts
//     immediately, like transaction recording; DELETING a transfer row
//     goes through the existing Sprint C confirmation untouched.
//   - Soft delete only (like every transaction): the Sprint C delete /
//     undo / edit flows operate on this row as-is.
//
// No direct `supabase.from(...)` calls here - all DB access goes through
// db/queries/transactions.js and db/queries/wallets.js.

import * as transactionQueries from '../db/queries/transactions.js';
import * as walletQueries from '../db/queries/wallets.js';

/** The built-in category every transfer row carries (config/categories.js default list). */
export const TRANSFER_CATEGORY = 'Transfer';

/** Ownership is not optional - fail loudly if a caller forgets to scope. */
function assertUserScope(userId, fnName) {
  if (!userId) {
    throw new Error(`${fnName} requires a userId - transfers queries must stay user-scoped.`);
  }
}

/**
 * Creates one transfer row for the caller.
 *
 * Payload contract: amount (number > 0, coerced via Number), both
 * endpoint wallet IDs (already name-resolved by the chat handler),
 * rawText (the user's message - searchable history, NOT NULL in the
 * schema), and sourceMessageId (generated by the chat handler exactly
 * like every transaction insert, unique-index dedupe key).
 *
 * Statuses: 'created' (transaction attached) | 'invalid_amount'
 * (non-finite or <= 0) | 'missing_endpoint' (either id absent) |
 * 'same_wallet' (both endpoints identical - nothing would move) |
 * 'not_found' (an endpoint id missing, archived-list lookup, or owned by
 * ANOTHER user - user-scoped query returns null) | 'archived' (an
 * endpoint is archived at commit time: a race with archiveWallet, since
 * the name resolver already excludes archived rows). Every non-'created'
 * status performs ZERO writes.
 */
export async function createTransfer(userId, payload = {}) {
  assertUserScope(userId, 'createTransfer');
  const { amount, fromWalletId, toWalletId, rawText, sourceMessageId } = payload;

  if (!sourceMessageId) {
    // Programming error, not a user error: the local dedupe id is
    // generated by the chat handler for every row it inserts.
    throw new Error('createTransfer requires sourceMessageId (generated by the chat handler).');
  }

  const numericAmount = Number(amount);
  if (!Number.isFinite(numericAmount) || numericAmount <= 0) {
    return { status: 'invalid_amount', amount };
  }
  if (!fromWalletId || !toWalletId) return { status: 'missing_endpoint' };
  if (fromWalletId === toWalletId) return { status: 'same_wallet' };

  // Commit-time re-check (user-scoped at the query layer): both
  // endpoints must be the caller's own wallets.
  const from = await walletQueries.getUserWalletById(fromWalletId, userId);
  const to = await walletQueries.getUserWalletById(toWalletId, userId);
  if (!from || !to) return { status: 'not_found' };
  if (from.archived_at || to.archived_at) return { status: 'archived' };

  const transaction = await transactionQueries.insertTransaction({
    user_id: userId,
    type: 'transfer',
    amount: numericAmount,
    category: TRANSFER_CATEGORY,
    raw_text: typeof rawText === 'string' ? rawText : '',
    confidence: 'high',
    source_message_id: sourceMessageId,
    prompt_version: null,
    wallet_id: from.id,
    to_wallet_id: to.id,
  });

  return { status: 'created', transaction };
}
